### ISSUE TITLE
Error in schematron Invoice. bad escaped characters

### ISSUE THREAD

**Issue by ConnectingEurope** [ConnectingEurope/eInvoicing-EN16931#229] opened 2020-09-11 15:46 UTC
We found that the current schematron file have incorrectly escaped characters i nsome of the rules. Please see attachment.

**Comment by ConnectingEurope** [comment] 2020-09-11 15:48
![Escape_character(1)](https://user-images.githubusercontent.com/52830282/92946427-2bec0e80-f446-11ea-8365-aad7f761fbfe.jpg)

**Comment by phax** [comment] 2020-09-11 15:48
Is that a duplicate of https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/220 ?

**Comment by ConnectingEurope** [comment] 2020-09-11 15:53
Originates from https://openpeppol.atlassian.net/browse/PEPPOL-2725

**Comment by oriol** [comment] 2020-09-17 09:34
@phax : That is okay. Only the “<“ must be escaped. The “>” don’t necessarily need to be escaped, even though it is considered best practise.

**Closed as completed by oriol** 2020-09-17 09:34 UTC
Labels: Format UBL
