### ISSUE TITLE
BR-CL-24 Cii - mime code ods/xslx

### ISSUE THREAD

**Issue by Malagand** [ConnectingEurope/eInvoicing-EN16931#291] opened 2021-07-27 13:18 UTC
Hello,

in EN16931-CII-validation is an extra space in 2 lines for mime type ods/xslx which need to be corrected. Issue is known an was properly fixed in EN16931-UBL-validation but not for Cii.

![image](https://user-images.githubusercontent.com/80773193/127159827-b5db90be-22f6-4b22-85e3-59b8fa79bfdf.png)

Best regards

Daniel Streng

**Comment by phax** [comment] 2021-07-27 13:19
Duplicate of #268 ?

**Comment by Malagand** [comment] 2021-07-27 13:41
Hi Philip, yes didn't notice it sorry. Just googled for Issue BR-CL-24. Assume this change will be part of next release 2.x?

**Comment by phax** [comment] 2021-07-27 13:43
As it was fixed on March 16th ,2021, it should be part of the 1.3.5 release and later.
When you stumbled upon this in the context of XRechnung, you need to wait for the next release of XRechnung - sorry.
hth

**Comment by Malagand** [comment] 2021-07-27 13:56
ok, that helps. Greetings to Vienna.

**Comment by phax** [comment] 2021-07-27 13:57
Thanks - greetings back :) Feel free to close the issue when you think it is done.

**Closed as completed** 2021-07-27 14:03 UTC
